apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  PORT: "3000"
  PRODUCT_SERVICE_URL: "http://product-service:3001"
  ORDER_SERVICE_URL: "http://order-service:3002"
  NODE_ENV: "production"
