apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_REPLICATION_USER: replicator
  POSTGRES_REPLICATION_PASSWORD: replicator
